[project]
name = "gans-data-diet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.3",
    "torch>=2.6.0",
]

[dependency-groups]
dev = [
    "gans-data-diet",
]

[tool.uv.sources]
gans-data-diet = { workspace = true }
